### ISSUE TITLE
suggestion: make more space for content

### ISSUE THREAD

**Issue by dwainm** [woocommerce/houston#3]
Idea: have a twitter like box above the first post so there can be more space for all other posts. The space to the left is a bit too much.

**Comment by mattyza** [comment]
To clarify, you'd like the post box to move above the posts list, right Dwain?  

## 

Matt Cohen
Chief Product Officer at WooThemes

http://woothemes.com/
http://matty.co.za/

**Comment by dwainm** [comment]
:+1:
