### ISSUE TITLE
When you write a long message, there is no way to publish it

### ISSUE THREAD

**Issue by JohnONolan** [woocommerce/houston#49]
Eg.

![image](https://f.cloud.github.com/assets/120485/1463772/9f4fd904-4536-11e3-9930-6420baf0de8c.png)

Probably needs some intelligent margins based on viewport size with max-height as a fallback

**Comment by jameskoster** [comment]
I was wondering when someone would find this :-D I'll look into it for the next release, kinda tricky though as the textarea is resized by a p2 core script. Might need to remove that.

In the mean time, if you shrink the browser window you can post long messages.

**Comment by coenjacobs** [comment]
Psssh, that is exactly the feedback you gave me @jameskoster when I reported this weeks ago! :wink:

**Comment by jameskoster** [comment]
ya, well, there's been no update since then. :p Go away @coenjacobs
