### ISSUE TITLE
Commenting/Replying Broken in Chrome

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/houston#51]
If I type a reply and click the reply button, nothing happens. :(

Other users of Houston are reporting this as well via Twitter. Seems to only have started in the last couple of days on the latest Chrome update.

**Comment by HelloTiago** [comment]
I just tested it here and it's working, but I keep getting a notification on the bottom of the page saying "Oops! Looks like you are not logged in. Please log in again.".

**Comment by mattyza** [comment]
I've experienced a similar notice on the default P2 theme previously as well.  

Please test with just P2 and advise if the same occurs. :)  

## 

Matt Cohen
Chief Product Officer at WooThemes

http://woothemes.com/
http://matty.co.za/

**Comment by HelloTiago** [comment]
Yap, same thing happens on the P2 theme.

**Comment by mattyza** [comment]
Then this is a bug in P2 and the server setup, not Houston. :)  

I've noticed this in general when using P2. It's what happens when you're not logged in and the system polls for data.

Refreshing the page should present a login screen, if you have login restrictions on your installation.  

## 

Matt Cohen
Chief Product Officer at WooThemes

http://woothemes.com/
http://matty.co.za/

**Comment by HelloTiago** [comment]
Okay, I'll look for the proper place to report it then :) I've logged out manually and logged back in, and it still happens, so it's probably something else.

**Comment by mattyza** [comment]
@ryanr14 Is the original issue (ie: not what @HelloTiago is referring to, which should be listed as an entirely separate issue, for future reference), still an issue on your end? :)

**Comment by mattyza** [comment]
@jameskoster I just experienced this when attempting to reply to a comment on our own P2.

My reply was snarky, so maybe Houston knows this and is blocking snarky replies, now? ;)

**Comment by jameskoster** [comment]
Hmm this seems to be working fine for me? Is it only latest Chrome? No other browsers?

I didn't touch the reply form so I'm wondering if this is also a parent p2 conflict.

**Comment by mattyza** [comment]
I believe I’m on the latest Chrome, yeah.  

Works fine for @kloon though?  

## 

Matt Cohen
Chief Product Officer at WooThemes

http://woothemes.com/
http://matty.co.za/

**Comment by kloon** [comment]
Err @mattyza you spoke to soon, can't post this morning as well :angry:

**Comment by jameskoster** [comment]
Pretty sure this will be a p2 issue. I can reply just fine so it's hard to debug. If/when it breaks for me I will investigate. Would appreciate any insight from one of you guys struggling to post.

**Comment by scottbasgaard** [comment]
Same here.

**Comment by kloon** [comment]
Believe @msdesign21 has the same problem

**Comment by jameskoster** [comment]
Confirmed issue exists in p2 parent. I actually think (hope) Chrome will be to blame here.

**Comment by msdesign21** [comment]
May help: http://wordpress.org/support/topic/posting-on-chrome-isnt-working-mac-osx

**Comment by mattyza** [comment]
Lance has already fixed and patched this in P2. I can confirm that this isn't a Houston issue. :)  

## 

Matt Cohen
Chief Product Officer at WooThemes

http://woothemes.com/
http://matty.co.za/
