### ISSUE TITLE
Replies Appearing On Unrelated Posts

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/houston#54]
The reply button appears on a 5th level reply http://cld.wthms.co/nTsf

When you add a reply to this it then attaches your reply to another unrelated post http://cld.wthms.co/2ZFs

**Comment by jameskoster** [comment]
Hmm actually this isn't the issue.

The problem occurs when you reply to a comment that has been pulled in via ajax without refreshing the page first. Not sure why but it's attaching the wrong postID to the reply form. Work fine if you refresh so there issue is in the AJAX somewhere.

Don't really have time to debug p2 js further so I'm just going to remove this reply link for now.
