### ISSUE TITLE
Mobile display needs to trigger at a higher resolution

### ISSUE THREAD

**Issue by hlashbrooke** [woocommerce/houston#7]
This is what it looks like on my phone: http://cl.ly/image/2T2U2N3t253z

There seems to three different layouts: the normal desktop layout, this one that I see on my phone, and the complete mobile layout where the sidebar is dropped and the menu is accessible from a button.

IMO, there only needs to be two layouts: the full desktop view, and the complete mobile view. The intermediate view (presumably for tablets and larger phones) can be dropped. The mobile view should trigger at the same point that the intermediate view triggers at the moment - that would mean that all phones (except perhaps the Galaxy Note) would see the proper mobile view.

**Comment by jameskoster** [comment]
This this might be related to the script p2 is loading. What resolution is your phone @hlashbrooke ?
