### ISSUE TITLE
New comment notification doesn't disappear on scroll

### ISSUE THREAD

**Issue by hlashbrooke** [woocommerce/houston#9]
New posts and comments are highlighted with a green border on the right as they appear. This notification for new posts disappears as you scroll down the page, but it doesn't disappear for comments. The notification will stay there until you refresh the page. The default P2 theme handles this by highlighting the post/comment and it disappears correctly on scroll.

**Comment by jameskoster** [comment]
Argh that's so crap, rather than just removing the 'new' class, the default p2 script actually sets the background color using jquery. Will have to go back to the background color as an indication of new posts / comments :-(
